'$schema' = "https://starship.rs/config-schema.json"

add_newline = false

palette = "catppuccin_mocha"

format = """
[ ](bg:blue)\
$sudo\
$username\
$mise\
[](fg:blue bg:red)\
$directory\
[](fg:red bg:green)\
$git_branch\
$git_status\
[](fg:green)\
\n\
$time\
$cmd_duration\
$c\
$lua\
$php\
$zig\
$rust\
$nodejs\
$golang\
$python\
$docker_context\
\n\
$character\
"""


[palettes.catppuccin_mocha]
c = "#00599C"
go = "#00ADD8"
lua = "#2C2D72"
zig = "#F7A41D"
mise = "#4DA9BE"
node = "#5FA04E"
rust = "#000000"
docker = "#2496ED"
python = "#3776AB"
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[cmd_duration]
min_time = 500
format = '[  $duration]($style)'
style = "bg:surface0 fg:text"

[character]
format = "╰$symbol "
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold blue)"
vimcmd_symbol = "[❮](bold blue)"
vimcmd_visual_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_replace_one_symbol = "[❮](bold purple)"

[directory]
style = "fg:crust bg:red"
format = "[ $path]($style)"
home_symbol = "󰋜"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"nvim" = ""
".dotfiles" = " dotfiles"
".config" = " config"
".cargo" = "🦀 .cargo"
"Music" = " Music"
"Pictures" = " Pictures"
"Documents" = "󰈙 Documents"
"Downloads" = " Downloads"

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:crust bg:green)]($style)'

[git_status]
style = "bg:green"
ahead = "⇡"
behind = "⇣"
conflicted = "="
staged = "[󰐙](fg:#008000 bg:green)"
stashed = "[](fg:#40a02b bg:green)"
deleted = "[](fg:#FF0000 bg:green)"
modified = "[](fg:#df8e1d bg:green)"
untracked = "[](fg:#800080 bg:green)"
diverged = ""
disabled = false
typechanged = ""
format = '[[($all_status$ahead_behind)](fg:crust bg:green)]($style)'

[sudo]
style = "fg:crust bg:blue"
symbol = "󱞾"
format = "[$symbol]($style)"
disabled = false

[username]
show_always = true
style_user = "fg:crust bg:blue"
format = "[ $user]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230"
format = '[[│ $time](fg:text)]($style)'

[aws]
symbol = "󰸏"
style = "bold yellow"
format = " [$symbol ($profile )(\\($region\\) )(\\[$duration\\] )]($style)"

[mise]
disabled = false
format = '[ $health ](fg:#FFFFFF bg:blue)'
symbol = "󱁤"
healthy_symbol = ""
unhealthy_symbol = ""

[c]
symbol = ""
style = "149 bold"
detect_extensions = ["c", "h", "cxx", "cpp", "hpp"]
format = '[ [](fg:c)[$symbol ($version)](fg:#FFFFFF bg:c)]($style)[](fg:c)'

[docker_context]
symbol = ""
format = '[ [](fg:docker)[$symbol $context](fg:#FFFFFF bg:docker)]($style)[](fg:docker)'

[golang]
symbol = ""
format = '[ [](fg:go)[$symbol ($version)](fg:#FFFFFF bg:go)]($style)[](fg:go)'

[lua]
symbol = ""
format = '[ [](fg:lua)[$symbol ($version)](fg:#FFFFFF bg:lua)]($style)[](fg:lua)'

[nodejs]
symbol = ""
format = '[ [](fg:node)[$symbol ($version)](fg:#FFFFFF bg:node)]($style)[](fg:node)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
format = '[ [](fg:python)[$symbol ($version)](fg:#FFFFFF bg:python)]($style)[](fg:python)'

[ruby]
symbol = ""
format = "[$symbol ($version)]($style)"

[rust]
symbol = ""
format = '[ [](fg:rust)[$symbol ($version)](fg:#FFFFFF bg:rust)]($style)[](fg:rust)'

[zig]
symbol = ""
format = "[ [](fg:zig)[$symbol ($version)](fg:black bg:zig)]($style)[](fg:zig)"
style = ""
